kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30001
    hostPort: 30001
- role: worker
- role: worker
networking:
  disableDefaultCNI: true
  podSubnet: 192.168.0.0/16

 #aws = sg
 # azure = nsg
 #gcp = firewall rules
 #metallb

 #istioctl verify install

 # k get crds | grep istio | wc -l
# k get ns --show-labels | grep istio

#kubectl label namespace <namespace-name> istio-injection=disabled

#curl -s -0 /dev/null <load balancer IP>/productpage

#kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.32.0/manifests/tigera-operator.yaml

#kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.32.0/manifests/custom-resources.yaml


#keda medium docs
#https://medium.com/@mgaurang123/keda-event-driven-autoscaling-for-kubernetes-that-actually-saves-you-money-42cc40c35415